### ISSUE TITLE
Fable 2

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-elmish/browser#11]
Could you please update dependencies to Fable.Core/Fable.PowerPack 2 (prerelease) and release a prerelease version?

**Comment by et1975** [comment]
Re-released v1.x as 2.0.0-beta-4, previous master is in the reverse-args branch.

**Comment by alfonsogarciacaro** [comment]
Sorry, I think I messed up with Fable.Import.Browser releases. There's a 1.2.0-beta-001 release (that latest Fable.Elmish.Browser beta is depending on) from last year that I don't know exactly what is doing there and I cannot find the code for it in the fable-import repository. I just published a 1.3.0 version to override, could you please update the dependency?

**Comment by et1975** [comment]
Released as beta-5
