### ISSUE TITLE
Impossible to use Program.toNavigable together with Program.runWith

### ISSUE THREAD

**Issue by toburger** [fable-elmish/browser#16]
### Description

I couldn't get `Program.toNavigable` to work with `Program.runWith`.

`toNavigable` produces a Program which discards the argument type of the previous Program.

### Repro code

```fsharp
Program.mkProgram init update view
|> Program.toNavigable parser urlUpdate
|> Program.runWith () // unit is the only possible argument
```

### Expected and actual results

My expectation would be that `toNavigable` carries on the argument type.
This means that the init function not only receives the route but also the init parameter.

#### Expected result:
`Program<'a, 'model, 'msg, 'view>` becomes `Program<'a, 'model, Navigable<'msg>, 'view>` where 'a is the argument to the init function.

#### Actual result:
`Program<'a, 'model, 'msg, 'view>` becomes `Program<unit, 'model, Navigable<'msg>, 'view>`

### Related information 

* elmish version: 2.0.3
* elmish-browser version: 2.1
* fable-compiler version: 2.0.10
* fable-core version: 2.0.1
* Operating system: Windows 10

**Comment by et1975** [comment]
You can curry your argument in: `Program.mkProgram (init your_arg) update view`, but I'll see if we can do what you ask w/o breaking existing code.

**Comment by toburger** [comment]
Hmm, I can live with your solution!
Only concern it is kind of an impure application in the elmish workflow, but a good enough workaround.

**Comment by et1975** [comment]
There's nothing "impure" about partial application, the only reason we have arg separately is because we want a function, not a value passed as `init`.
Unfortunately I don't see a way to pass an extra argument *unless it's a `unit`* w/o breaking too much, and passing a `unit` will result in ugly `init` like `unit->Route->'model*Cmd<'msg>` for everyone who doesn't need to pass an additional arg.

**Comment by toburger** [comment]
No problem! Partial application is perfectly okay!
What I meant is that the argument isn't provided at the last possible point in time before the elmish engine kicks in... But that's negligible.. ;)
