### ISSUE TITLE
i32 and non ints

### ISSUE THREAD

**Issue by davidtme** [fable-elmish/browser#2]
### Description

Using the i32 in a Parser doesn't work as expected.

### Repro code
url: http://localhost:8080/#/product/create

`
map (PageRequest.ProductDetails) (s "product" </> i32) 
`

### Expected and actual results

Parser should skip over the map but it crashes with `Uncaught Error: Input string was not in a correct format.`

Looking at the code I think https://github.com/fable-elmish/browser/blob/master/src/parser.fs#L81 should be using a TryParse?

**Comment by et1975** [comment]
Yes, thank you. Will you PR this?
