### ISSUE TITLE
Naming conflict with the new Fable.Browser.

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-elmish/browser#20]
### Description

Please provide a succinct description of your issue.

### Repro code

Please provide the F# code to reproduce the problem.
Ideally, it should be possibe to easily turn this code into a unit test.

### Expected and actual results

Please provide the expected and actual results.

### Related information 

* elmish version:
* fable-compiler version:
* fable-core version:
* Operating system:

**Comment by et1975** [comment]
Are we not sufficiently distinct with `Elmish.` prefix?

**Comment by alfonsogarciacaro** [comment]
Sorry, something weird happened when reporting the issue, please discard this one and check #21
