### ISSUE TITLE
3.0.1 not on nuget (needed to fix #22)

### ISSUE THREAD

**Issue by rommsen** [fable-elmish/browser#24]
### Description
I am currently updating https://github.com/SAFE-Stack/SAFE-ConfPlanner to the latest and greates and I am getting the following error when building:
```
ERROR in ./.fable/Fable.Elmish.Browser.3.0.0/parser.fs
Module Error (from ./node_modules/fable-loader/index.js):
C:/src/SAFE-ConfPlanner/.fable/Fable.Elmish.Browser.3.0.0/parser.fs(272,19): (272,46) error FSHARP: A unique overload for method 'TryParse' could not be determined based on type information prior to this program point. A type annotation may be needed. Candidates: System.Int32.TryParse(s: System.ReadOnlySpan<char>, result: byref<int>) : bool, System.Int32.TryParse(s: string, result: byref<int>) : bool (code 41)
```

It seems that this is fixed in 3.0.1 (https://github.com/elmish/browser/issues/22) but this version is not published to nuget. Would be awesome if you could do this.

![grafik](https://user-images.githubusercontent.com/743946/59668316-8e5d4d00-91b8-11e9-880d-32f01c645082.png)

**Comment by et1975** [comment]
Sorry, was sure I released it this time... turns out PublishNuget target is missing from the Publish chain, doh!

**Comment by et1975** [comment]
<img width="589" alt="nailed it" src="https://user-images.githubusercontent.com/623703/59687691-e42af880-91aa-11e9-9bd1-2457f6dac694.png">

Nailed it this time!

**Comment by rommsen** [comment]
Thanks Eugene!
