### ISSUE TITLE
TypeError: 对象不支持此操作 (object does not support this operation)

### ISSUE THREAD

**Issue by albertwoo** [fable-elmish/browser#25]
### Description

Navigation.newUrl does not work on IE11. I got error says object does dot support this operation.

Below code can be a workaround for me:
``` fharp
  let goToUrl url =
    Browser.Dom.window.history.pushState((), "", url)
    let evt = Browser.Dom.document.createEvent("Event")
    evt.initEvent("NavigatedEvent", false, false)
    Browser.Dom.window.dispatchEvent evt |> ignore
    Cmd.none
```

### Expected and actual results

Should work on IE 11

### Related information 

* elmish version: 3.0.1
* fable-compiler version: 2.3.12
* fable-core version: 3.0
* Operating system: windows 10

**Comment by MangelMaxime** [comment]
This seems to be a limitation of IE11 indeed [Source can I use](https://caniuse.com/#search=CustomEvent)

Did you try to configure babel to support IE11 too? [Doc](https://babeljs.io/docs/en/babel-preset-env)

I think if configured correctly babel will convert the code to IE11 compatible code.

**Comment by albertwoo** [comment]
Will try that in the future. Thanks to pint this out.

**Comment by SCullman** [comment]
As I just run into the same issue: IE11 requires now a polyfill for _CustomEvent_.
(Added because information was kind of hidden in links)

**Comment by kspeakman** [comment]
@MangelMaxime Babel will not polyfill CustomEvent. It depends on core-js for polyfill, which has decided not to polyfill it (see [here](https://github.com/zloirock/core-js/issues/354)). So because of the change made to Elmish Browser (I believe [here](https://github.com/elmish/browser/commit/7b4676a103283a2926179708ade41bb72137a907#diff-3a9f899fb2aec54ef55f963a4241cc78) ), Navigate.newUrl will not be compatible with IE11 unless a separate polyfill is also imported.

cc @et1975

**Comment by et1975** [comment]
@kspeakman thanks for pointing this out, could you recommend a package that polyfills `CustomEvent`?

**Comment by kspeakman** [comment]
Here's what I did.

```console
npm install --save custom-event-polyfill
```

Then before Program.mk{...}.

```fsharp
Fable.Core.JsInterop.importAll "custom-event-polyfill/polyfill.js"
```

**Comment by albertwoo** [comment]
@et1975 you can also just copy the function from below link and paste it to your index.html in script block:
https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#Polyfill
