### ISSUE TITLE
add Parser.pathUrl

### ISSUE THREAD

**Issue by forki** [fable-elmish/browser#28]
The current parser works on Browser.Types.Location. It would be great for React Native to have one that works on strings. Can we use the following?

```fs
    let urlParser (url:string) =
        let pos = url.IndexOf "?"
        if pos >= 0 then
            let path = url.Substring(0,pos)
            let search = url.Substring(pos)
            parse configParser path (parseParams search)
        else
            parse configParser url Map.empty
```

**Comment by et1975** [comment]
This repo is for browsers specifically (where `Location` is guaranteed to be present) and I guess I'm not clear on how you'd use it in RN environment. Can you describe?
We could split parser out into its own package I suppose and maybe put this code into elmish.react...

**Comment by forki** [comment]
https://facebook.github.io/react-native/docs/linking#basic-usage

It allows you to do deep linking into your app. I'd like to parse those
links and feed into elmish

Eugene Tolmachev <notifications@github.com> schrieb am Mi., 27. Nov. 2019,
16:03:

**Comment by et1975** [comment]
Makes sense, yeah I think I'll extract the url parser into itsown package.

**Comment by forki** [comment]
Cool. Thanks

Eugene Tolmachev <notifications@github.com> schrieb am Mi., 27. Nov. 2019,
16:57:

**Comment by et1975** [comment]
Released in the new package https://github.com/elmish/urlParser as Fable.Elmish.UrlParser@1.0.0-alpha-1 and it's now available for CLR as well (Elmish.UrlParser@1.0.0-alpha-1).
elmish-urlParser will be a dependency for elmish-browser from v4 onward.

**Comment by forki** [comment]
Awesome. Thanks

Eugene Tolmachev <notifications@github.com> schrieb am Fr., 29. Nov. 2019,
21:38:
