### ISSUE TITLE
Base64 string padding char seems to trip up parser

### ISSUE THREAD

**Issue by alexswan10k** [fable-elmish/browser#31]
### Description

For base 64 encoded strings, they are often padded with an = character. This seems to break the parser and return None for a query string parameter with padding.

##### Workaround
```
String.replace ("=", "@") //or some other character that isn't in the standard base64 set and is allowed in a query param
//https://en.wikipedia.org/wiki/Base64
```
### Repro code
```
let route = s "someRoute"  <?> stringParam "data"
```

Then run any query string with padding. For example:
domain.com/someRoute?data=YQ==
where data is "a" in this context.

### Expected and actual results
* Expected
** data = Some "YQ=="
* Actual
** data = None
### Related information 

* elmish version: Fable.Elmish (3.0.6)
* fable-compiler version: 2.4.11
* fable-core version:Fable.Core (3.1.3) 
* Operating system: Windows 10

Hopefully this is quite clear. I imagine it is probably due to the parser maybe splits on = rather than parse based on previous context - eg a parameter can only start with ? or & and is followed by an =.

I know that base64 isnt that common, but its handy for passing around complex serialised graphs compactly. Tokens are also also sometimes sent back to a client this way, although they do use hashtag navigation.

Let me know if anything else is needed.

**Comment by et1975** [comment]
thanks, I'll take a look.

**Comment by et1975** [comment]
So it seems you should URL encode the base64 strings precisely because it can contain special characters.

**Comment by alexswan10k** [comment]
Ah yes indeed. Sorry I should have looked this up before opening - I actually tried this myself and had a heap of other problems so assumed this wouldn't work. I was under the impression an equivalent OAUTH example i had does not urlencode, but perhaps that was an incorrect assumption.

As it stands I actually found a totally different way to handle my issue so happy to close this.
