### ISSUE TITLE
Fable Compiler 3 Fails to compile

### ISSUE THREAD

**Issue by AngelMunoz** [fable-elmish/browser#35]
### Description
I'm testing the waters by upgrading to Fable3
and all went smoothly except for an internal binding which
```
C:/Users/scyth/source/repos/PalabratorFS/src/.fable/Fable.Elmish.Browser.3.0.0/parser.fs(272,19): (272,46) error FSHARP: A unique overload for method 'TryParse' could not be determined based on type information prior to this program point. A type annotation may be needed.
Known type of argument: string
Candidates:
System.Int32.TryParse(s: System.ReadOnlySpan, result: byref) : bool

System.Int32.TryParse(s: string, result: byref) : bool (code 41)

Watching src
```

refers to this code
```fsharp
let internal intParamHelp =
    Option.bind
        (fun value ->
            match System.Int32.TryParse value with
            | (true,x) -> Some x
            | _ -> None)

```
It fixes locally if `...(fun (value: string) -> ...` is added but I'm not sure if that's the actual fix

Let me know if this issue should go here or in the fable repository

<details>
<summary>Fable3 Compiler Output</summary>
<pre>
┌──────────────────>
│PalabratorFS •NET v5.0.100-rc.2.20479.15 via ⬢ v14.13.0 on aws🧇(us-west-2)
└─> on  main [!]
[😏]~>  dotnet fable watch src --run webpack-dev-server
Fable: F# to JS compiler 3.0.0-nagareyama-beta-002
Thanks to the contributor! @KevinLamb
src> cmd /C "dotnet" restore App.fsproj
  Determining projects to restore...
C:\Users\scyth\source\repos\PalabratorFS\src\App.fsproj : warning NU1608: Detected package version outside of dependency constraint: Feliz.UseListener 0.6.2 requires FSharp.Core (>= 4.7.2 && < 5.0.0) but 
version FSharp.Core 5.0.0 was resolved.
  Restored C:\Users\scyth\source\repos\PalabratorFS\src\App.fsproj (in 356 ms).
Parsing src\App.fsproj...
Initializing F# compiler...
Compiling src\App.fsproj...
F# compilation finished in 9803ms
Compiled src\.fable\Fable.Promise.2.0.0\PromiseImpl.fs
Compiled src\.fable\Fable.Elmish.3.1.0\prelude.fs
Compiled src\.fable\Fable.Elmish.Browser.3.0.0\prelude.fs
Compiled src\.fable\Fable.React.7.0.1\Fable.ReactDom.fs
Compiled src\.fable\Fable.React.7.0.1\Fable.React.fs   
Compiled src\.fable\Fable.Elmish.3.1.0\cmd.fs
Compiled src\.fable\Fable.React.7.0.1\Fable.React.Extensions.fs
Compiled src\.fable\Fable.Elmish.Browser.3.0.0\navigation.fs   
Compiled src\.fable\Fable.Elmish.3.1.0\program.fs
Compiled src\.fable\Fable.React.7.0.1\Fable.React.Standard.fs
Compiled src\.fable\Fable.React.7.0.1\Fable.React.Props.fs
Compiled src\.fable\Fable.React.7.0.1\Fable.React.ReactiveComponents.fs
Compiled src\.fable\Fable.React.7.0.1\Fable.ReactServer.fs
Compiled src\.fable\Fable.React.7.0.1\Fable.React.Hooks.fs
Compiled src\.fable\Fable.React.7.0.1\Fable.React.FunctionComponent.fs
Compiled src\.fable\Fable.Elmish.3.1.0\ring.fs
Compiled src\.fable\Fable.React.7.0.1\Fable.React.Isomorphic.fs
Compiled src\.fable\Fable.Elmish.Browser.3.0.0\parser.fs
Compiled src\.fable\Fable.React.7.0.1\Fable.React.Helpers.fs
Compiled src\.fable\Fable.Elmish.React.3.0.1\common.fs
Compiled src\.fable\Fable.Elmish.React.3.0.1\react.fs
Compiled src\.fable\Feliz.1.14.0\StyleTypes.fs
Compiled src\.fable\Fable.Elmish.HMR.4.0.1\bindings.fs
Compiled src\.fable\Feliz.1.14.0\Types.fs
Compiled src\.fable\Feliz.1.14.0\ReactTypes.fs
Compiled src\.fable\Feliz.1.14.0\Interop.fs
Compiled src\.fable\Feliz.1.14.0\Transform.fs
Compiled src\.fable\Feliz.1.14.0\Fonts.fs
Compiled src\.fable\Fable.Elmish.HMR.4.0.1\hmr.fs
Compiled src\.fable\Feliz.1.14.0\Key.fs
Compiled src\.fable\Feliz.1.14.0\Colors.fs
Compiled src\.fable\Fable.Elmish.React.3.0.1\react-native.fs
Compiled src\.fable\Feliz.1.14.0\TextDecorationStyle.fs
Compiled src\.fable\Feliz.1.14.0\TextDecorationLine.fs
Compiled src\.fable\Feliz.1.14.0\BorderStyle.fs
Compiled src\.fable\Feliz.1.14.0\Length.fs
Compiled src\.fable\Fable.Elmish.HMR.4.0.1\common.fs
Compiled src\.fable\Feliz.1.14.0\TransitionProperty.fs
Compiled src\.fable\Fable.Promise.2.0.0\Promise.fs
Compiled src\.fable\Feliz.1.14.0\ReactDOM.fs
Compiled src\.fable\Feliz.UseListener.0.6.2\PromiseRejectionEvent.fs
Compiled src\.fable\Thoth.Json.4.0.0\Types.fs
Compiled src\.fable\Feliz.UseElmish.1.4.1\UseElmish.fs
Compiled src\.fable\Feliz.UseListener.0.6.2\Listener.fs
Compiled src\.fable\Fable.Elmish.Debugger.3.2.0\Fable.Import.RemoteDev.fs
Compiled src\.fable\Thoth.Json.4.0.0\Extra.fs
Compiled src\Types.fs
Compiled src\.fable\Fable.Elmish.Debugger.3.2.0\debugger.fs
Compiled src\.fable\Feliz.1.14.0\Html.fs
Compiled src\.fable\Feliz.1.14.0\React.fs
Compiled src\.fable\Feliz.1.14.0\Styles.fs
Compiled src\.fable\Feliz.1.14.0\Properties.fs
Compiled src\Playground.fs
Compiled src\App.fs
Compiled src\Admin.fs
Compiled src\.fable\Feliz.Router.3.2.0\Router.fs
Compiled src\Main.fs
Compiled src\.fable\Thoth.Json.4.0.0\Encode.fs
Compiled src\Components\Game.fs
Compiled src\.fable\Thoth.Json.4.0.0\Decode.fs
Fable compilation finished in 1896ms
C:/Users/scyth/source/repos/PalabratorFS/src/.fable/Fable.Elmish.Browser.3.0.0/parser.fs(272,19): (272,46) error FSHARP: A unique overload for method 'TryParse' could not be determined based on type information prior to this program point. A type annotation may be needed.

Known type of argument: string

Candidates:
 - System.Int32.TryParse(s: System.ReadOnlySpan<char>, result: byref<int>) : bool
 - System.Int32.TryParse(s: string, result: byref<int>) : bool (code 41)
Watching src
</pre>
</details>

### Repro code

clone this repository
- https://github.com/AngelMunoz/PalabratorFS
- pnpm (or npm) install 
- dotnet fable watch src --run webpack-dev-server

### Expected and actual results
I don't expect to have errors compiling the libraries

### Related information 

* elmish version: N/A
* fable-compiler version: 3.0.0-nagareyama-beta-002
* fable-core version: N/A
* Operating system: Windows 10.0.19041

**Comment by et1975** [comment]
Thanks for the report.
That sounds like valid fix, a PR would be welcome.

**Comment by AngelMunoz** [comment]
@et1975 my bad, I just went to check the source code, and seems it has been fixed for a while, I just needed to include the updated package reference in my fsproj. I Will close this, thanks
