### ISSUE TITLE
TryParse' could not be determined based on type information prior to this program point

### ISSUE THREAD

**Issue by albertwoo** [fable-elmish/browser#36]
### Description

Build failed with fable 3:

.fable/Fable.Elmish.Browser.3.0.0/parser.fs(272,19): (272,46) error FSHARP: A unique overload for method 'TryParse' could not be determined based on type information prior to this program point. A type annotation may be needed

* fable-compiler version: 3.0.0-nagareyama-rc-009

**Comment by et1975** [comment]
Duplicate of #22 ?

**Comment by albertwoo** [comment]
https://github.com/elmish/hmr/issues/27
