### ISSUE TITLE
Should we handle the onChangeRef differently?

### ISSUE THREAD

**Issue by MangelMaxime** [fable-elmish/browser#37]
### Description

Now that v4 support `termination`, it is possible that the user will spawn several Elmish program.

Meaning that this is possible for them to register `Program.toNavigable` several times. This will result in `onChangeRef` being override by the last program which registered.

- Program1 register with `Program.toNavigable`
- Program2 register with `Program.toNavigable`
- Program1 exit, it will try to `unsubscribe()` but it will remove the events listeners of `Program2` instead of `Program1`

Originally, we exposed the `unsubscribe()` API for `Elmish.HMR` but now that `Elmish.Browser` can terminate itself, I think it is possible to move the `let mutable private onChangeRef : obj -> obj =` inside [`let toNavigableWith`](https://github.com/elmish/browser/blob/e93226b0646511edd6435218531a4156af9e46ef/src/navigation.fs#L79) scope meaning that the reference will be scoped to the Program instance.

**Comment by et1975** [comment]
Good catch, want to open a PR?

**Comment by MangelMaxime** [comment]
Yes, I will do.
