### ISSUE TITLE
How to notify the user that the Parser module has been moved to its own pacakge?

### ISSUE THREAD

**Issue by MangelMaxime** [fable-elmish/browser#47]
### Description

With the release of v4, the urlParser module has been removed from this package and moved to its own package.

How can we inform the user of that fact? As right now, if they upgrade to v4 the project is going to fail to compile without much explanation.

Should we keep an empty shell in place with `Obsolete` message asking the user to use the new package?

**Comment by et1975** [comment]
It [a dependency of Browser](https://github.com/elmish/browser/blob/v4.x/src/Fable.Elmish.Browser.fsproj#L15), why would it matter that we moved it out?

**Comment by MangelMaxime** [comment]
This is related to the slack message you answered to:

![image](https://user-images.githubusercontent.com/4760796/166260725-a17d91c6-9732-498d-a98d-87e9c662f90e.png)

But you are right that this is a dependency of the Elmish.Browser package.

I didn't check the source of the error that jan.bizub mentioned. I just asked him if he could provide more details about it.

**Comment by MangelMaxime** [comment]
After a second check by jan.bizub, he confirmed that this was actually working and problem the IDE not up to date with the changes.
