### ISSUE TITLE
How to turn ?name=tom&age=42 into nice data?

### ISSUE THREAD

**Issue by ctaggart** [fable-elmish/browser#5]
How do you create a query parser with multiple values like [is described](https://github.com/fable-elmish/browser/blob/master/src/parser.fs#L219)?

```
?name=tom&age=42
```

Say you wanted that to be a record of:
``` fsharp
type PersonQuery = { name: string; age: string }
```

**Comment by et1975** [comment]
I'll add it to the docs.

**Comment by ctaggart** [comment]
Thanks @et1975, looking forward to it!

**Comment by et1975** [comment]
Released the updated docs, see if it makes sense?

**Comment by ctaggart** [comment]
It does. Thank you! I'm having a good time with Elmish.

**Comment by et1975** [comment]
Thank you! I'm fan of your work, hoping to ditch C# protobuf and use generative Froto provider some day :)
