### ISSUE TITLE
Fix for Fable substring behavior for v4

### ISSUE THREAD

**Issue by NickDarvey** [fable-elmish/browser#50]
### Description

[A fix](https://github.com/elmish/browser/commit/933132ea19a1931aa95bd8730f24dfad2fa8d91e#diff-6f2c91a3a3c5274b824b327312da840550aa4edd1b75195df9ff18427ba4a4b8) for #30 was made to the v3 branch but not made to the v4 branch.

### Repro code

Same as #30.

### Expected and actual results

Same as #30.

### Related information 

* elmish version: 4.0.0-beta-3
* fable-compiler version: >2.4.12
* fable-core version: >3

**Comment by et1975** [comment]
Fixed in beta-5, thanks for point it out.
