### ISSUE TITLE
How to parse a string literal

### ISSUE THREAD

**Issue by lambdakris** [fable-elmish/browser#6]
### Description

Referring to [Parsing Routes](https://fable-elmish.github.io/browser/routing.html#Parsing-routes) in the docs, I was not able to parse a string literal.

### Repro code

```
open Elmish.Browser.UrlParser

parse (s "blog") "blog"
```

### Expected and actual result

I figured it would compile and yield Some "blog", however, the expression doesn't compile due to the following error:
```
Type mismatch. Expecting a 
  'Parser<('a -> 'a)>, 'a>'
but given a
  'Parser<('a -> 'a), ('a -> 'a)>'
the types ''a' and ''a -> 'a' cannot be unified
```

### Related information 

* fable-elmish version: 0.9.2
* fable-compiler version: 1.1.9
* fable-core version: 1.1.7
* Operating system: Windows 10

**Comment by et1975** [comment]
`s "blog"` in your example refers to a "static" portion - something that is expected to be present in the input, but is not captured, ie the parser as specified has no instructions to extract something and I guess the compiler can't infer the types involved.
`parse str "blog"` would do what you expect it to do.

**Comment by lambdakris** [comment]
I was actually looking into how to get something like the following:

```
type Route = Home | Search of string
let routes = 
    [ map Home (s "home")
      map Search (s "search" </> str) ]
parse (oneOf routes)
```
or just
```
parse (map Home (s "home"))
```

Which works, but I was just hoping there was a way to build a "match a string" expression without applying the map function...

**Comment by et1975** [comment]
The idea of this parser-combinator module is that a single type unifies the parsed out values, what you are asking for can only be represented by a DU, so you need to pass the `map` function to construct it.
